/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

public enum ErrorCode
{
  kSuccess = 0,
  kKeyNotFound = 1,
  kError = 2,
}
